### ISSUE TITLE
Re-write the entire rendering / graphics system to use opengl 3.0 or higher.

### ISSUE THREAD

**Issue by Paul-Wortmann** [Paul-Wortmann/Frost_and_Flame#10]
Re-write the entire rendering / graphics system to use OpenGL 3.2. or higher.
I might as well just re-write the game form scratch while I'm at it....

**Comment by shirishag75** [comment]
so what is the status as of now, it works with opengl 3.1 or you need something better ?

**Comment by Paul-Wortmann** [comment]
Yeah, Frost and Flame now uses modern OpenGL, 3.x working flawlessly.
Although I have yet to move all of Frost and Flame over to 3D, basically I am working on a new XML parser for Frost and Flame that will allow for easier 3D model importing, a lot of other features are waiting on that. I think the direction I took was a good choice, the game is a lot more robust and allows for a lot of future potential. Although it also means that the next working release of Frost and Flame will take some time. All in all engine development goes well. ;)
