### ISSUE TITLE
no documentation about roboengine library

### ISSUE THREAD

**Issue by shirishag75** [Paul-Wortmann/Frost_and_Flame#60]
Hi there, 

After sometime I tried to compile and got the following :-

    $ cmake .
    -- The C compiler identification is GNU 5.2.1
    -- The CXX compiler identification is GNU 5.2.1
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Performing Test COMPILER_SUPPORTS_CXX11
    -- Performing Test COMPILER_SUPPORTS_CXX11 - Success
    -- Performing Test COMPILER_SUPPORTS_CXX0X
    -- Performing Test COMPILER_SUPPORTS_CXX0X - Success
    ERROR Couldn't find the RoboEngine library.
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
    -- checking for one of the modules 'sdl2'
    -- checking for one of the modules 'SDL2_image'
    -- checking for one of the modules 'SDL2_mixer'
    -- checking for one of the modules 'SDL2_net'
    -- checking for one of the modules 'SDL2_ttf'
    -- Found PhysFS: /usr/lib/x86_64-linux-gnu/libphysfs.so  
    -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
    -- checking for one of the modules 'glew'
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/shirish/games/frost_and_flame
    
So you can see where the error is. I read readme.md but there is/was nothing about the roboengine library.

Also trying to compile it breaks because of the above :-

    $ make
    Scanning dependencies of target frost_and_flame
    [ 25%] Building CXX object CMakeFiles/frost_and_flame.dir/src/gamecore.cpp.o
    In file included from /home/shirish/games/frost_and_flame/src/gamecore.cpp:27:0:
    /home/shirish/games/frost_and_flame/src/gamecore.hpp:28:38: fatal error: ../RoboEngine/maingame.hpp: No such file or directory
     #include <../RoboEngine/maingame.hpp>
                                          ^
    compilation terminated.
    CMakeFiles/frost_and_flame.dir/build.make:62: recipe for target 'CMakeFiles/frost_and_flame.dir/src/gamecore.cpp.o' failed
    make[2]: *** [CMakeFiles/frost_and_flame.dir/src/gamecore.cpp.o] Error 1
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/frost_and_flame.dir/all' failed
    make[1]: *** [CMakeFiles/frost_and_flame.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by Paul-Wortmann** [comment]
I have had a bit of time recently to put some work into Frost and Flame and have rewritten quite a bit, I have also integrated a subset of the single threaded RoboEngine into the code base and will continue to work on Frost and Flame with and integrated engine for the foreseeable future as it is more easily distributable in this form.
Currently the game is unplayable and only a blue screen is visible, a bit more work is needed on a few core components such as the graphics engine and entity component system.
Frost and Flame compiles straight from the repo using the CMakeLists file, as such this issue is deemed resolved.
